"""Suns Chan persistent-agent core + Phase 0 foundation boundaries."""

from .activities import (
    ActivityCandidate,
    ActivitySelection,
    generate_activities,
    select_activity,
)
from .acquisition import (
    AcquisitionReport,
    BrowserDiscoverySource,
    CandidateEvaluation,
    CapabilityAcquirer,
    CapabilityCandidate,
    DiscoverySource,
    DownloadRecord,
    Downloader,
    MockDiscoverySource,
    evaluate_candidate,
)
from .api import ChatRequest, ChatResponse, MemoryQuery, TaskRequest, route_table
from .affect import AffectDelta, AffectEvidence, AttentionWeights, apply_affect, attention_weights, collect_evidence, expression_note, selection_bias, update_affect
from .avatar import AvatarAdapter, MockAvatar, PresentationState, build_presentation, present_text
from .autonomy import AutonomyEngine, RecoveryInfo, RunReport, StepReport, translate_probe_to_shell
from .broker import SandboxBroker, SandboxFileResult, SandboxPolicy
from .browser import BrowserDocument, BrowserProvider, HttpBrowserProvider, MockBrowserProvider
from .capability import CapabilityGap, CapabilityRecord, CapabilityStore, CapabilityUsage, detect_capability_gap, recommend_capability
from .curiosity import Curiosity, CuriosityStore
from .experience import Experience, experiences_of_session, record_experience, related_experiences
from .chat import build_chat_decide, handle_command, inspect_audit, inspect_memory, inspect_state
from .comms import CommunicationProposal, DispatchResult, MockChannel, approval_brief, dispatch, scrub_secrets
from .config import SandboxSettings, SensorSettings, CommsSettings, VoiceSettings, AvatarSettings, Settings, TelemetrySettings
from .consolidation import ConsolidationResult, LearningConsolidationResult, consolidate, consolidate_learning, consolidation_due
from .context import KnowledgeStanza, affect_section, build_knowledge_section, build_user_understanding_section, environment_section, graph_section, label_record, telemetry_section, understanding_label
from .core import AgentCore, Decision, GoalProposal, TurnContext
from .embeddings import EmbeddingProvider, HashingEmbedder, OllamaEmbedder, cosine_similarity
from .environment import EnvEvent, EnvObservation, EnvState, FakeEnvironment
from .events import Event, EventBus, user_message_received
from .graph import Association, GraphEdge, GraphIndex, GraphNode, GraphPath, associate, build_index, format_paths
from .identity import IdentitySeed
from .ingest import ClaimEvaluation, IngestResult, acquire, acquire_api, chunk_text, evaluate_claim, find_fresh_source, knowledge_for_event, refresh_temporal
from .knowledge import BeliefExplanation, KnowledgeRecord, KnowledgeStore, SourceRef
from .learning import LearningTracker, PreferenceState, tend_interests
from .learned import (
    ConfidenceBreakdown,
    LearnedObject,
    LearnedStore,
    LearningExplanation,
    compute_confidence,
    decay_stale,
    explain_learning,
    mine_patterns,
    mine_preferences,
    mine_skills,
    mine_strategies,
    status_for,
    strategy_bonus_for,
)
from .llm import EchoProvider, LLMMessage, LLMRequest, LLMResponse, provider_from_settings
from .memory import EventLedger, MemoryEvent, tokenize
from .observability import TaskTrace, TraceStep, get_logger, health_check, setup_logging
from .ranking import DEFAULT_WEIGHTS, RankedCandidate, ScoredCandidate, rank, recency_decay, weighted_score
from .reflection import ReflectionFinding, ReflectionReport, reflect
from .policy import ActionRequest, ActionVerdict, PolicyGate
from .projects import ProjectView, format_projects, list_projects
from .proxmox_provider import ProxmoxCredentials, ProxmoxSandboxProvider
from .public import DiscoveryResult, IdentityEvaluation, MockPublicSource, PublicSource, discover_public, evaluate_identity
from .runtime import AgentRuntime, Stage, Task, TaskResult
from .sandbox import SandboxRequest
from .sandbox_controller import ExperimentProposal, ExperimentRecord, SandboxController, validate_proposal
from .sensors import CallableSensorProvider, ScriptedSensorProvider, SensorHub, SensorReading, ThresholdRule, WakeDecision, proxmox_vm_readings
from .sources import ApiSource, FetchedDocument, HttpSource, MockApiSource, MockSearchSource, MockWebSource, SearchHit, SearchSource, SourceAdapter, extract_text
from .self_model import SelfModel, build_self_model
from .session import AutonomySession, SessionStore
from .schemas import DECISION_JSON_SCHEMA, DecisionValidationError, parse_decision, parse_decision_json
from .state import AgentState
from .storage import Database
from .telemetry import (
    FileTelemetrySource,
    NormalizedTelemetry,
    RawTelemetry,
    ScriptedTelemetrySource,
    TelemetryCollectionReport,
    TelemetryCollector,
    TelemetrySource,
    TelemetryState,
    classify_importance,
    mine_telemetry_understanding,
    normalize,
    promote_telemetry,
    record_telemetry_experience,
    summarize_recent_telemetry,
    unpromoted_telemetry,
)
from .tools import ToolRegistry, ToolResult, ToolSpec, default_registry
from .understanding import (
    KIND_CONFIDENCE_CAP,
    KIND_DEFAULT_CONFIDENCE,
    UnderstandingExplanation,
    UnderstandingRecord,
    UnderstandingSource,
    UnderstandingStore,
    mine_understanding,
    refresh_understanding,
)
from .voice import MockVoiceInput, MockVoiceOutput, VoiceBus, VoiceInputProvider, VoiceOutputProvider
from .vm_sandbox import (
    ArtifactRecord,
    GuestResult,
    MockSandboxProvider,
    SnapshotInfo,
    VMSpec,
    VMResources,
)
from .vm_template import TemplateBuild, VMTemplateSpec, cloud_init_user_data

__all__ = [
    "ActionRequest",
    "ActionVerdict",
    "AcquisitionReport",
    "ActivityCandidate",
    "ActivitySelection",
    "AffectDelta",
    "AffectEvidence",
    "AgentCore",
    "AgentRuntime",
    "AgentState",
    "AttentionWeights",
    "Association",
    "AutonomyEngine",
    "AutonomySession",
    "AvatarAdapter",
    "BeliefExplanation",
    "BrowserDiscoverySource",
    "BrowserDocument",
    "BrowserProvider",
    "build_chat_decide",
    "build_index",
    "build_knowledge_section",
    "build_presentation",
    "build_self_model",
    "build_user_understanding_section",
    "CallableSensorProvider",
    "CandidateEvaluation",
    "CapabilityAcquirer",
    "CapabilityCandidate",
    "CapabilityGap",
    "CapabilityRecord",
    "CapabilityStore",
    "CapabilityUsage",
    "ChatRequest",
    "ChatResponse",
    "chunk_text",
    "ClaimEvaluation",
    "classify_importance",
    "collect_evidence",
    "CommunicationProposal",
    "compute_confidence",
    "consolidate",
    "ConsolidationResult",
    "consolidate_learning",
    "consolidation_due",
    "cosine_similarity",
    "Curiosity",
    "CuriosityStore",
    "Decision",
    "DecisionValidationError",
    "DECISION_JSON_SCHEMA",
    "default_registry",
    "Database",
    "detect_capability_gap",
    "DispatchResult",
    "dispatch",
    "decay_stale",
    "DiscoveryResult",
    "DiscoverySource",
    "discover_public",
    "DownloadRecord",
    "Downloader",
    "EchoProvider",
    "EmbeddingProvider",
    "environment_section",
    "EnvEvent",
    "EnvObservation",
    "EnvState",
    "Event",
    "EventBus",
    "EventLedger",
    "ExperimentProposal",
    "ExperimentRecord",
    "explain_learning",
    "expression_note",
    "extract_text",
    "evaluate_candidate",
    "FakeEnvironment",
    "FetchedDocument",
    "FileTelemetrySource",
    "find_fresh_source",
    "format_paths",
    "format_projects",
    "generate_activities",
    "get_logger",
    "GraphEdge",
    "GraphIndex",
    "GraphNode",
    "GraphPath",
    "graph_section",
    "GuestResult",
    "HashingEmbedder",
    "health_check",
    "HttpBrowserProvider",
    "HttpSource",
    "IdentityEvaluation",
    "IdentitySeed",
    "IngestResult",
    "inspect_audit",
    "inspect_memory",
    "inspect_state",
    "knowledge_for_event",
    "KnowledgeRecord",
    "KnowledgeStanza",
    "KnowledgeStore",
    "label_record",
    "LearningConsolidationResult",
    "LearningTracker",
    "LearnedObject",
    "LearnedStore",
    "LearningExplanation",
    "LLMMessage",
    "LLMRequest",
    "LLMResponse",
    "MemoryEvent",
    "MemoryQuery",
    "mine_telemetry_understanding",
    "mine_understanding",
    "MockApiSource",
    "MockAvatar",
    "MockBrowserProvider",
    "MockChannel",
    "MockDiscoverySource",
    "MockPublicSource",
    "MockSandboxProvider",
    "MockSearchSource",
    "MockVoiceInput",
    "MockVoiceOutput",
    "MockWebSource",
    "normalize",
    "NormalizedTelemetry",
    "OllamaEmbedder",
    "PolicyGate",
    "PreferenceState",
    "PresentationState",
    "ProjectView",
    "ProxmoxCredentials",
    "ProxmoxSandboxProvider",
    "proxmox_vm_readings",
    "promote_telemetry",
    "PublicSource",
    "rank",
    "RankedCandidate",
    "RawTelemetry",
    "recency_decay",
    "record_experience",
    "record_telemetry_experience",
    "ReflectionFinding",
    "ReflectionReport",
    "reflect",
    "related_experiences",
    "refresh_temporal",
    "refresh_understanding",
    "recommend_capability",
    "route_table",
    "RunReport",
    "SandboxBroker",
    "SandboxController",
    "SandboxFileResult",
    "SandboxPolicy",
    "SandboxRequest",
    "ScoredCandidate",
    "ScriptedSensorProvider",
    "ScriptedTelemetrySource",
    "SearchHit",
    "SearchSource",
    "select_activity",
    "selection_bias",
    "SelfModel",
    "SensorHub",
    "SensorReading",
    "SensorSettings",
    "SessionStore",
    "Settings",
    "setup_logging",
    "Stage",
    "status_for",
    "strategy_bonus_for",
    "StepReport",
    "SourceAdapter",
    "SourceRef",
    "SnapshotInfo",
    "summarize_recent_telemetry",
    "Task",
    "TaskResult",
    "TaskRequest",
    "TaskTrace",
    "TelemetryCollectionReport",
    "TelemetryCollector",
    "TelemetrySettings",
    "TelemetrySource",
    "TelemetryState",
    "telemetry_section",
    "tend_interests",
    "ThresholdRule",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "TraceStep",
    "translate_probe_to_shell",
    "TurnContext",
    "update_affect",
    "UnderstandingExplanation",
    "UnderstandingRecord",
    "UnderstandingSource",
    "UnderstandingStore",
    "understanding_label",
    "unpromoted_telemetry",
    "user_message_received",
    "weighted_score",
]
